export type SessionOutcome = 'resolved' | 'escalated' | 'abandoned';

export interface SessionLog {
  id: string;
  title: string;
  startedAt: number;
  messageCount: number;
  toolCalls: number;
  outcome: SessionOutcome;
  durationMin: number;
}

// Fixed sample history for the Logs page. These are not generated by the
// simulation and do not change while the app runs: this is where a fork plugs
// in its real past sessions. Times are minutes before `now`, so the list never
// looks stale however long ago the app was built.
const SAMPLE_SESSIONS: [
  id: string,
  title: string,
  minutesAgo: number,
  messageCount: number,
  toolCalls: number,
  outcome: SessionOutcome,
  durationMin: number,
][] = [
  ['s-014', 'Refund for order #4790', 25, 6, 3, 'resolved', 4],
  ['s-013', 'Summarise weekly support tickets', 70, 4, 4, 'resolved', 6],
  ['s-012', 'Draft release notes v2.3', 140, 8, 5, 'resolved', 9],
  ['s-011', 'Chargeback dispute, passed to billing', 260, 12, 6, 'escalated', 17],
  ['s-010', 'Password reset loop', 400, 7, 2, 'resolved', 5],
  ['s-009', 'Bulk export timed out', 700, 5, 3, 'abandoned', 8],
  ['s-008', 'Refund for order #4766', 1100, 6, 3, 'resolved', 4],
  ['s-007', 'Update shipping address', 1500, 5, 2, 'resolved', 3],
  ['s-006', 'Draft release notes v2.2', 1900, 9, 5, 'resolved', 11],
  ['s-005', 'Account deletion request', 2600, 10, 4, 'escalated', 14],
  ['s-004', 'Invoice copy for March', 3300, 4, 1, 'resolved', 2],
  ['s-003', 'Summarise weekend ticket backlog', 4400, 3, 2, 'abandoned', 3],
  ['s-002', 'Refund for order #4701', 5800, 11, 5, 'escalated', 16],
  ['s-001', 'Cancel a subscription mid-cycle', 7200, 6, 2, 'abandoned', 7],
];

/** Fourteen made-up sessions from the last five days, newest first. */
export function createSessionLogs(now: number): SessionLog[] {
  return SAMPLE_SESSIONS.map(([id, title, minutesAgo, messageCount, toolCalls, outcome, durationMin]) => ({
    id,
    title,
    startedAt: now - minutesAgo * 60_000,
    messageCount,
    toolCalls,
    outcome,
    durationMin,
  }));
}
